all_rules = [
    "Każdy głupi potrafi zawierać transakcje handlowe, ale trzeba geniuszu, wiary i wytrwałości by stworzyć markę.",
    "Za każdym razem, kiedy widzisz biznes, który odnosi sukces, oznacza to, że ktoś kiedyś podjął odważną decyzję.",
    "Kieruj swoim interesem, bo inaczej on tobą pokieruje.",
    "Puste kieszenie nigdy nie powstrzymały nikogo przed podjęciem działania. Mogą to zrobić tylko puste głowy i puste serca.",
    "Zdolność uczenia się szybciej od swojej konkurencji może być jedyną długotrwałą przewagą, jaką nad nimi posiadasz.",
    "Jeśli jest coś, czego nie potrafimy zrobić wydajniej, taniej i lepiej niż konkurenci, nie ma sensu, żebyśmy to robili i powinniśmy zatrudnić do wykonania tej pracy kogoś, kto zrobi to lepiej niż my.",
    "Życie po prostu jest. Trzeba płynąć wraz z nim.",
    "Życie to zagadka, nie trać czasu, bo jej nie rozwiążesz.",
    "Podróżować to żyć.",
    "Nasze życie jest takim, jakim uczyniły je nasze myśli.",
    "Życia nie mierzy się ilością oddechów, ale ilością chwil, które zapierają dech w piersiach.",
    "Życie jest komedią dla tych, którzy patrzą, a tragedią dla tych, którzy czują.",
    "Jak komuś życie krzywo się ułożyło (...) i jest sam, to robi się trochę dziwny i nieraz głupie pomysły przychodzą mu do głowy.",
    "Życie to piękny teatr, niestety repertuar marny.",
    "Są w życiu sytuacje, w których musisz sobie powiedzieć 'dam radę' i iść dalej.",
    "Nie ma takich problemów, które pewnego dnia by się nie skończyły.",
    "Trzeba mieć, co się chce! I trzeba żyć, jak się chce!",
    "Wkrótce wynajdą mikroskop tak potężny, że zaczną odkrywać, że życie jest puste.",
    "Okres Oświecenia to już przeszłość. Teraz żyjemy w epoce Oszustwienia.",
    "Czasami nie chodzi o to, aby się zmieniło na lepsze. Najczęściej chodzi o to, aby zmieniło się cokolwiek.",
    "Znacznie łatwiej zachować przez całe życie wierność sercu niż rozsądkowi.",
    "Nie po to się żyje razem, żeby się sprawdzić, tylko żeby się wspomagać i chronić nawzajem swoje bolesne miejsca.",
    "Branie czegoś na serio przez długi czas utrudnia życie.",
    "Życie jest wspaniałe, należy tylko spoglądać na nie przez właściwe okulary.",
    "Sztuka trwa długo, życie krótko.",
    "Trzeba kochać życie, aby je przeżywać, i trzeba przeżywać życie, aby je kochać.",
    "Istota życia jest dobrym użyciem czasu.",
    "Na tym polega wartość życia, że płaci się za nie nawet życiem.",
    "Odpowiedniejszą rzeczą jest śmiać się z życia, niż lamentować.",
    "Źle jest żyć w okowach konieczności, żadna jednak konieczność nie zmusza nas do życia.",
    "Każdy pragnie żyć długo, ale nikt nie chciałby starości.",
    "Nie żyje się samą miłością, żyje się też za pieniądze.",
    "Życie jest większe od legend, bo w życiu jest prawda.",
    "Krótkie życie nie pozwala nam żywić odległych nadziei.",
    "Kobiety żyją dłużej od mężczyzn. Szczególnie wdowy.",
    "Lepiej jest umrzeć, kiedy człowiek chce żyć, niż umierać wtedy, kiedy człowiek chce już tylko umrzeć.",
    "To reguła, że ludzie pijani życiem trzeźwieją w miarę wypijania większej dawki alkoholu.",
    "Człowiek, który żyje jak zboże, staje się słomą historii.",
    "Kiedy mężczyzna mówi, że wyczerpał życie, to można zawsze być pewnym, iż życie go wyczerpało.",
    "Swoje niepowodzenia ludzie elegancko nazywają doświadczeniem życiowym.",
    "Kto żyje bez szaleństwa, mniej jest rozsądny, niż mniema.",
    "Absurdalność daje się wyrazić tylko za pomocą humoru",
    "Błąd jest przywilejem filozofów, tylko głupcy nie mylą się nigdy",
    "Cały kłopot polega na tym, że głupcy są pewni siebie, a mądrzy pełni wątpliwości",
    "Celem demokracji jest powszechna przeciętność",
    "Chciałbym mieć umysł tak giętki, jak mają ciało akrobaci",
    "Chcieliśmy dobrze, a wyszło jak zawsze",
    "Chociaż wiedza stwarza problemy, to ignorancja ich nie rozwiąże",
    "Ci, co najbardziej zasługują na pochwały, najlepiej znoszą krytykę",
    "Ci, którzy są z siebie zadowoleni, mają zawsze zły gust",
    "Poprzedni minister finansów zapewniał, że już niedługo wszyscy będziemy zarabiali powyżej średniej.",
    "Dodawanie kombinacji liniowej kolumn przy rozwiązywaniu układu równań liniowych jest jak dodawanie kartofli do spirytusu.",
    "Kto nie ryzykuje, ten dzieci nie ma",
    "Przerwany jest niezdrowy",
    "Jak wszyscy to babcia też",
    "Nie wiem, nie znam się, zarobiony jestem",
    "Najważniejsza jest pierwsza ćwiartka, a potem to już leci",
    "Co to jest nic? Niektórzy mówią że połówka na głowę",
    "Tutaj będzie całka po 'dr' ale jak ktoś nie wymawia "r" to może być po 'dl' ",
    "Na drzewku to się można co najwyżej powiesić",
    "Różnica między granicą, a granicą niewłaściwą jest taka jak między demokracją, a demokracją socjalistyczną",
    "Różnica pomiędzy granicą, a granicą niewłaściwą jest taka jak między krzesłem, a krzesłem elektrycznym",
    "Liczby urojone nie są wcale jakieś urojone, to są normalne liczby rzeczywiste tylko, że trochę… inne…",
    "Cosinus to jest śmieć!",
    "A Pan X otrzymał z kolokwium… a nie, Pana nie było. A tak, oddawał Pan krew. Dobrze. Przynajmniej Pan coś pożytecznego zrobił.",
    "Tw. Eulera → Tw. Ojlera → Tw. Oj(cho)lera",
    "Należy przyjąć takie generalne założenie, że to co robimy ma sens",
    "Ta całka jest tak ważna..tak ważna, że hej!",
    "Co mogę zrobić z szeregiem liczbowym? Niiic, siąść i płakać",
    "Nie będę podawał bardziej abstrakcyjnych przykładów, żeby nie przeabstracholować",
    "Rozrasta się ten wzór jak nowotwór za przeproszeniem",
    "Tutaj będzie element neutralny, a tu wyjdzie C, B, A… Hmm CBA, to niedobrze, to na drugi raz zmienimy litery",
    "Twierdzenie o trzech ciągach. Innymi słowy jeżeli dwóch funkcjonariuszy idzie na komisariat to ten którego prowadzą też trafi na komisariat",
    "Tutaj jest całka bez całkowania…jak Bruce Lee w wejściu smoka, walka bez walki",
    "Lepiej coś innego obalić niż twierdzenie",
    "Egzamin jest zdalnie, więc nie jestem w stanie sprawdzić, czy macie notatki, czy nie. To można mieć jakieś tam notatki",
    "(…) 95-procentowy - czyli mocny jak spirytus - przedział ufności.",
    "Całkowanie przez części jest czasami jak powiedzenie zamienił stryjek siekierkę na kijek",
    "Moja lewa ręka to śmierć, a prawej sam się boję",
    "Tanio skóry nie sprzedam",
    "Po maturze chodziliśmy na kremówki",
    "No jak Pan Jezus powiedział?",
    "Tak jak Pan Jezus powiedział",
    "Zrzucając zbędne kilogramy, wcale nie trzeba korzystać z cudownych diet. Wystarczy bułka z bananem!",
    "W kolanach i plecach mnie nie łupie, więc chyba będzie dobrze",
    "Łubu dubu, łubu dubu, niech żyje nam prezes naszego klubu! Niech żyje nam! To śpiewałem ja – Jarząbek.",
    "Coco jamboo i do przodu! – to moje hasło. Dobre, nie?",
    "Jak kochać to księcia, jak kraść to miliony.",
    "A historii tego swetra i tak byś nie zrozumiał.",
    "Przyszłem wcześniej, gdyż nie miałem co robić.",
    "A kto umarł, ten nie żyje.",
    "Dżentelmen nie pije przed południem.",
    "Żeby tak się stało, żebym nie musiał ciepłej pić!",
    "No sąd sądem, ale sprawiedliwość musi być po naszej stronie.",
    "Żadnej roboty nie wezmę, nie wiem, nie znam się, nie orientuję się, zarobiony jestem!",
    "Diabeł, to taki Anioł co wstąpił do nie tego pubu co trzeba i wypił odrobinę za dużo.",
    "Pije by paść,padam by wstać, wstaję by żyć, żyję by pić.",
    "Jak do mnie mówisz to milcz!",
    "Dwóch półgłówków głowy nie czyni.",
    "Piwo to dowód na to, że Bóg nas kocha i chce byśmy byli szczęśliwi."
]
